export const LOG_IN_REQUEST = 'LOG_IN_REQUEST';
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_IN_FAILURE = 'LOG_IN_FAILURE';
export const LOG_OUT = 'LOG_OUT';
export const LOG_IN_ERROR_SERVER = 'LOG_IN_ERROR_SERVER';

export const INQUIRER_REQUEST = 'INQUIRER_REQUEST';
export const INQUIRER_SUCCESS = 'INQUIRER_SUCCESS';
export const INQUIRER_ERROR_SERVER = 'INQUIRER_ERROR_SERVER';
export const INQUIRER_ADD = 'INQUIRER_ADD';

export const QUESTION_REQUEST = 'QUESTION_REQUEST';
export const QUESTION_SUCCESS = 'QUESTION_SUCCESS';
export const QUESTION_ERROR_SERVER = 'QUESTION_ERROR_SERVER';

export const TEST_ADD_SUCCESS = 'TEST_ADD_SUCCESS';

export const USER_AUTH_ERROR = 'USER_AUTH_ERROR';
export const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS';

export const CATEGORY_ADD_SUCCESS = 'CATEGORY_ADD_SUCCESS';
